[2024-03-31T22:15:52.477+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: one_task_dag.one_task manual__2024-03-31T22:15:49.060268+00:00 [queued]>
[2024-03-31T22:15:52.484+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: one_task_dag.one_task manual__2024-03-31T22:15:49.060268+00:00 [queued]>
[2024-03-31T22:15:52.484+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-31T22:15:52.484+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-03-31T22:15:52.484+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-31T22:15:52.518+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): one_task> on 2024-03-31 22:15:49.060268+00:00
[2024-03-31T22:15:52.521+0000] {standard_task_runner.py:55} INFO - Started process 22765 to run task
[2024-03-31T22:15:52.525+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2024-03-31T22:15:49.060268+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmpqkz9ndt_']
[2024-03-31T22:15:52.526+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask one_task
[2024-03-31T22:15:52.585+0000] {task_command.py:388} INFO - Running <TaskInstance: one_task_dag.one_task manual__2024-03-31T22:15:49.060268+00:00 [running]> on host codespaces-cbabfc
[2024-03-31T22:15:52.665+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abhi
AIRFLOW_CTX_DAG_ID=one_task_dag
AIRFLOW_CTX_TASK_ID=one_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-31T22:15:49.060268+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-31T22:15:49.060268+00:00
[2024-03-31T22:15:52.666+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-03-31T22:15:52.667+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hello, linkd learning!" > /workspaces/hands-on-Introductton-data-engineering-4395021/lab/createthisfile.txt']
[2024-03-31T22:15:52.675+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T22:15:52.676+0000] {subprocess.py:93} INFO - /usr/bin/bash: /workspaces/hands-on-Introductton-data-engineering-4395021/lab/createthisfile.txt: No such file or directory
[2024-03-31T22:15:52.676+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-31T22:15:52.682+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-31T22:15:52.685+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20240331T221549, start_date=20240331T221552, end_date=20240331T221552
[2024-03-31T22:15:52.722+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 22765)
[2024-03-31T22:15:52.741+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-03-31T22:15:52.751+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
